# Generated by Django 5.2.4 on 2025-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('noodles', 'Noodles'), ('rice', 'Rice Dishes'), ('appetizer', 'Appetizers'), ('dessert', 'Desserts')], default='noodles', max_length=20),
        ),
    ]
