# Generated by Django 5.2.4 on 2025-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish/'),
        ),
    ]
