# Generated by Django 5.2.5 on 2025-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150x150/81c408/ffffff?text=User', max_length=500, null=True),
        ),
    ]
