# Generated by Django 5.2.4 on 2025-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_comment_delete_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="social/picture"),
        ),
    ]
