# Generated by Django 5.2.4 on 2025-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_comment_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=2000)),
                ("image", models.ImageField(blank=True, null=True, upload_to="social")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
